server:
  port: 8081
  servlet:
    context-path: /shirobyjwt
spring:
  redis:
    host: 172.52.0.2
    password: redis@tct_dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shirobyjwt?useSSL=true&serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: huhailong
  mail:
    host: smtp.exmail.qq.com
    username: huhailong@huhailong.vip
    password: Hhl.vip110120119
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: "javax.net.ssl.SSLSocketFactory"
mybatis-plus:
  type-aliases-package: vip.huhailong.shirobyjwt.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
