server:
  port: 8081
  servlet:
    context-path: /shirobyjwt
spring:
  redis:
    host: 192.168.1.110
    password: huhailong
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.110:3306/shirobyjwt?useSSL=true&serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hhl@MySQL_1121
  mail:
    host: smtp.exmail.qq.com
    username: huhailong@huhailong.vip
    password: ************
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: "javax.net.ssl.SSLSocketFactory"
mybatis-plus:
  type-aliases-package: vip.huhailong.shirobyjwt.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server-mail:
  host: 'https://www.huhailong.vip/shirobyjwt/page/enableUser?token='
  url: 'https://www.huhailong.vip/webproject/shirobyjwt'
  form: 'huhailong@huhailong.vip'
file:
  upload:
    path: '/data/img/avatar/'
  url: 'https://www.huhailong.vip/img/avatar/'
